### ISSUE TITLE
socks4 do not work

### ISSUE THREAD

**Issue by R3XZT** [h12w/socks#14]
2020/06/20 13:36:12 Get "https://www.google.com": net/http: Transport.Dial hook returned (nil, nil)
2020/06/20 13:36:55 Get "https://www.google.com": EOF

Worker proxies, sample code used

`dialSocksProxy := socks.Dial("socks4://45.129.201.209:4145")
	tr := &http.Transport{Dial: dialSocksProxy}
	httpClient := &http.Client{Transport: tr}
	resp, err := httpClient.Get("https://www.google.com")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatal(resp.StatusCode)
	}
	buf, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
fmt.Println(string(buf))`

**Comment by h12w** [comment]
Thanks for spotting this. It is fixed now, could you please update the package and try it again?
I'll close the ticket but please feel free to reopen it if there are still problems.
