### ISSUE TITLE
Timeout does not work with fasthttp.Client

### ISSUE THREAD

**Issue by Numenorean** [h12w/socks#18]
Hello, I've faced with an issue when timeout param doesn't work with fasthttp client. Here is my func which i pass as an field Dial to the fasthttp.Client

```go
func(addr string) (net.Conn, error) {
			dialer := socks.Dial(proxyAddr + "?timeout=4s")
			return dialer("tcp", addr)
		}
```
and prepare the client:
```go
fasthttp.Client{
		Dial: prepareProxy(proxy),
	}
```
I must admit that with a valid proxy it works

**Comment by h12w** [comment]
I found and fixed an issue where the timeout is not applied during the TCP dialing but only works after the connection is established. Could you fetch the latest `v1.0.3` and give it a try?

**Comment by Numenorean** [comment]
@h12w thank you so much for replaying right away, now it works
